# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_components_+', to='products.Product'),
        ),
    ]
