# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161016_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_components_+', to='products.Product'),
        ),
    ]
